### ISSUE TITLE
Error shiny

### ISSUE THREAD

**Issue by loerasg** [daattali/ggExtra#10]
With the upgrade of shiny says "No layers in plot" which should be the graph:

**Comment by daattali** [comment]
You're right, since upgrading to shiny 0.12.0.9001 I do see that
message.... thanks for letting me know.  I can't figure out the problem yet

---
http://deanattali.com

**Comment by daattali** [comment]
Opened issue with shiny https://github.com/rstudio/shiny/issues/841

**Comment by daattali** [comment]
fixed, thanks for the quick bug report!
