### ISSUE TITLE
All file paths must be under 100 characters

### ISSUE THREAD

**Issue by daattali** [daattali/ggExtra#105]
The package is not being accepted into CRAN because some image file paths are over 100 chars long.

https://win-builder.r-project.org/incoming_pretest/ggExtra_0.8_20180403_085949/Windows/00check.log

**Comment by crew102** [comment]
We could just not include all of tests/ in the tarball uploaded to cran, as the package isn't tested on cran. Either that or shorten those paths. Do you have a preference?

Also, can we wait until #104 and #87 are closed before resubmitted to CRAN? I should be able to close those this week.

**Comment by daattali** [comment]
Good call - as long as they're still tested on travis, they can be omitted
from cran. Sure can wait

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

Want to improve your Shiny skills? Try my new interactive, online video
course *Shiny Case Studies*
<https://www.datacamp.com/courses/building-web-applications-in-r-with-shiny-case-studies>

**Comment by crew102** [comment]
can we re-open? the solution of ignoring tests dir doesn't work b/c we test against the built package on travis, which means we run tests on a package which doesn't include tests dir

**Comment by crew102** [comment]
actually i'm just gonna close this again (along with a few other few issues i just opened) in a single pr, so i wouldn't both re-opening

**Comment by daattali** [comment]
> we test against the built package on travis, which means we run tests on a package which doesn't include tests dir

Good catch...
