### ISSUE TITLE
Consider removing `data` `x` `y` parameters from ggMarginal()

### ISSUE THREAD

**Issue by daattali** [daattali/ggExtra#115]
Following the discussion in https://github.com/daattali/ggExtra/pull/110

The `data` `x` `y` parameters are an old artefact that resulted from creating this package/function initially without any long term vision. They cannot be used correctly in anything besides very simple plots. They don't add any features, they're purely for convenience and save the end user one line of code. I'm not even sure if people use them.

Removing them will be a major breaking change as these are 3 of the first 4 arguments, but it may be worthwhile.

**Comment by crew102** [comment]
I don't think we should deprecate these params. I don't think they were that bad of a design decision (though I agree that ideally they wouldn't exist), at least not enough to warrant breaking changes.

**Comment by daattali** [comment]
I don't want to introduce such a breaking change, closing
