### ISSUE TITLE
Error in ggplot2::aes_string(x, y)

### ISSUE THREAD

**Issue by IndrajeetPatil** [daattali/ggExtra#117]
I am not sure if I am doing anything wrong, but the `ggMarginal` function doesn't seem to be working properly when used with the `data` argument. Here is a fully reproducible example:

``` r

# loading needed libraries
library(ggExtra)
library(ggplot2)

# preparing the plot
p <-
  ggplot(data = iris,
         mapping = aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point()

# adding marginals
ggMarginal(p)
```

![](https://i.imgur.com/bPd9piw.png)

``` r

# using the data argument to get the same plot
ggExtra::ggMarginal(data = iris,
                    x = Sepal.Length,
                    y = Sepal.Width)
#> Error in ggplot2::aes_string(x, y): object 'Sepal.Length' not found
```

Created on 2018-05-08 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by daattali** [comment]
The x and y parameters should be strings, you need to put quotes around them

**Comment by IndrajeetPatil** [comment]
Sorry, so stupid. Tidyverse has spoiled me.
