### ISSUE TITLE
Hi. I am having a lot of trouble getting this to work. First, the grid package isn't available for the R version I have (latest) and then even though the package is loaded, I get a msg saying to '...please install gridExtra' What am I missing?

### ISSUE THREAD

**Issue by dniemeier** [daattali/ggExtra#12]
Hi. I am having a lot of trouble installing gridExtra. First, grid doesn't install under the current version of R and then when I try running running the package I get "Error: `gridExtra` package is required for this function to work. Please install it." even though the package is installed. Help?

**Comment by daattali** [comment]
Note that `ggExtra` and `gridExtra` are two different packages. My package is `ggExtra` and it needs you to have installed `gridExtra` as a prerequisite. Are you sure you have `gridExtra` installed? Run the following command and see what you get:

```
packageVersion("gridExtra")
```

**Comment by dniemeier** [comment]
Hi, thanks.

I finally got it to work by just installing gridExtra - in your instructs
on github, you have the following:

"You need to have the grid and gridExtra packages installed for this
function."

Somehow, if you try to install grid, it messes up gridExtra. Then you have
to restart the R session. But I got it working!

[image: Inline image 1]


Deb Niemeier, Ph.D., P.E.
Professor
Director, Sustainable Design Academy
Editor, Sustainable Cities and Society
Dept of Civil and Environmental Engineering
University of California
One Shields Ave
Davis, CA 95616
(530) 752-8918
dniemeier@ucdavis.edu

**Comment by daattali** [comment]
Installing `gridExtra` will already take care of installing `grid` so I'll update the docs
