### ISSUE TITLE
Error running ggMarginal

### ISSUE THREAD

**Issue by paternogbc** [daattali/ggExtra#13]
First, thank you very much for developing such a nice package! 

I am having this error when running the function 'ggMarginal'

> Error in data.frame(x = .Primitive("log10"), PANEL = c(1L, 1L, 1L, 1L,  : 
  arguments imply differing number of rows

Any idea how to solve the problem?

Maybe this is related to the log10 in the formula in ggplot2.

The code used:

> p1 <- ggplot(dat.crop, aes(y = log10(AGr), x = log10(herb + 1))) +
                    geom_point(size = 3, color = "tomato")+
                    geom_smooth(method = "lm")
ggMarginal(p1, type = "histogram")

Thanks in advance

**Comment by daattali** [comment]
@paternogbc thanks for the report, it took a while to debug this but I think I was able to solve it.  Please install the latest version of ggExtra from github and let me know if the problem persists

**Comment by paternogbc** [comment]
@daattali thank you very much for this fix! Now it is working just fine!
