### ISSUE TITLE
plots don't print in-line in R Notebooks

### ISSUE THREAD

**Issue by Aariq** [daattali/ggExtra#133]
`ggMarginal()` plots don't print in-line or in the Viewer tab (i.e. they don't print at all) in R Notebooks.
[ggExtra notebook bug.Rmd.zip](https://github.com/daattali/ggExtra/files/2620729/ggExtra.notebook.bug.Rmd.zip)

**Comment by crew102** [comment]
Hey @Aariq , a few notes:

* In order to view the ggMarginal plot inline in an R Notebook, you need to follow the example given in https://github.com/daattali/ggExtra/issues/89#issuecomment-381923199. Try changing your example to the following 2 chunk alternative:

```
---
title: "R Notebook"
output: html_notebook
---
```{r}
library(ggplot2)
library(ggExtra)

p <- ggplot(trees, aes(x = Height, y = Girth)) + geom_point() +
  geom_smooth(method = "lm")

p_marg <- ggMarginal(p, type = "histogram")
```

```{r}
library(grid)
grid.newpage()
grid.draw(p_marg)
```

* R Notebooks behave a bit differently than normal R Markdown documents when it comes to the preview feature. According to RStudio:

> The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.

...so if you want to see your ggMarginal plot in a preview, you have to run the code chunks responsible for creating the plot first.

**Comment by Aariq** [comment]
Thanks! Sorry I didn't find #89 before posting this.  Is there a reason why `grid.draw()` isn't the default print method?  It would be nice if this just "worked", if you know what I mean.

**Comment by crew102** [comment]
It actually is.

https://github.com/daattali/ggExtra/blob/4468f2113ecdd4d4fa2f8d380f843d2ac917b4db/R/ggMarginal.R#L191-L194

I didn't keep up with #89 so I'm not sure why ggMarginal needs to use the 2-chunk approach to printing in notebooks/Rmarkdown docs.

**Comment by daattali** [comment]
I'm still not sure why notebooks/rmd behave this way, and whether or not this is a big. If you follow the links in #89 you'll see this is not a resolved question. This information is also available in the README (which is, admittedly, a bit long). If you solved the problem (even though we don't know the root of the issue), you can close the issue

**Comment by crew102** [comment]
Hey @Aariq , thanks for attempting to fix...Unfortunately your fix would re-introduce the problem fixed in https://github.com/daattali/ggExtra/issues/48, so I'm thinking we leave things as is for now.

**Comment by Aariq** [comment]
Got it.
