### ISSUE TITLE
Cannot add ggproto objects together

### ISSUE THREAD

**Issue by idavydov** [daattali/ggExtra#136]
Hi,

Sorry, maybe this was already discussed before.

This code does not work:

``` r
library(tidyverse)
tibble(a=1:10, b=a**2) %>%
  ggplot(aes(a, b)) +
  geom_point() %>%
  ggExtra::ggMarginal(type="histogram")
#> Error: Cannot add ggproto objects together. Did you forget to add this object to a ggplot object?
```

While this does:
``` r
library(tidyverse)
p <- tibble(a=1:10, b=a**2) %>%
  ggplot(aes(a, b)) +
  geom_point()
ggExtra::ggMarginal(p, type="histogram")
```

![](https://i.imgur.com/SMjO5Wk.png)

Created on 2019-01-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by crew102** [comment]
Hi @idavydov , this syntax won't work b/c `%>%` is taking precedence over `+` , so the example you gave gets evaluated like this: 

```r
(tibble(a=1:10, b=a**2) %>% ggplot(aes(a, b))) +
 (geom_point() %>% ggExtra::ggMarginal(type="histogram"))
```

`ggMarginal()` obviously needs more than just a layer (i.e., `geom_point()`) to do its thing, hence the error. You can override the precedence if you'd like, which should fix things:

```r
library(tidyverse)
(tibble(a=1:10, b=a**2) %>%
  ggplot(aes(a, b)) +
  geom_point()) %>%
  ggExtra::ggMarginal(type="histogram")
```

**Comment by idavydov** [comment]
Thanks a lot for your explanation, that is very helpful.
