### ISSUE TITLE
Estrange behaviour: ggMarginal (p1, type = "histogram")

### ISSUE THREAD

**Issue by paternogbc** [daattali/ggExtra#14]
Dear @daattali,

I am using ggExtra on a shiny app. I dont know why, but today the rendered plot changed and the histogram is now a "rug" like plot. Any advise on that?
 
See below a small reproducible example.

``` r
library(ggplot2); library(ggExtra)
set.seed(30)
df1 <- data.frame(x = rnorm(500, 50, 10), y = runif(500, 0, 50))
(p1 <- ggplot(df1, aes(x, y)) + geom_point() + theme_bw())
```

![](http://i.imgur.com/VSyHn5H.png)

``` r
ggMarginal(p1, type = "histogram")
#> Scale for 'x' is already present. Adding another scale for 'x', which
#> will replace the existing scale.
```

![](http://i.imgur.com/8RfrXKX.png)

**Comment by daattali** [comment]
I just tried your code and it run fine, I see the normal expected plot.  Maybe one of your packages has been updated and is interfering?  Do you remember what packages you updated recently?  Here's my `sessionInfo()`

```
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggExtra_0.2.3 ggplot2_1.0.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.0      digest_0.6.8     MASS_7.3-43      grid_3.2.2       plyr_1.8.3       gtable_0.1.2    
 [7] magrittr_1.5     scales_0.3.0     stringi_0.5-5    reshape2_1.4.1   proto_0.3-10     labeling_0.3    
[13] tools_3.2.2      stringr_1.0.0    munsell_0.4.2    colorspace_1.2-6 gridExtra_2.0.0 
```

**Comment by paternogbc** [comment]
Maybe... I have updated many packages recently... But my `sessionInfo()` looks very similar:
I will continue to investigate and give you a feedback. Thanks anyway!

    R version 3.2.2 (2015-08-14)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 14.04.3 LTS

    locale:
    [1] LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C               LC_TIME=pt_BR.UTF-8       
    [4] LC_COLLATE=pt_BR.UTF-8     LC_MONETARY=pt_BR.UTF-8    LC_MESSAGES=pt_BR.UTF-   8   
    [7] LC_PAPER=pt_BR.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
    [10] LC_TELEPHONE=C             LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C       

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] ggExtra_0.2.3      ggplot2_1.0.1.9003

    loaded via a namespace (and not attached):
    [1] labeling_0.3      colorspace_1.2-6  scales_0.3.0.9000 plyr_1.8.3        tools_3.2.2      
    [6] gtable_0.1.2      gridExtra_2.0.0   Rcpp_0.12.0       grid_3.2.2        munsell_0.4.2

**Comment by paternogbc** [comment]
Got it!

It was something related to ggplot2.

> Error in get(Info[i, 1], envir = env) : 
  lazy-load database '/home/paterno/R/x86_64-pc-linux-gnu-library/3.2/ggplot2/R/ggplot2.rdb' is corrupt
Além disso: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1
Erro: package or namespace load failed for ‘ggplot2’

Removed ggplot2, installed again... restarted R session and it is working again!

Sorry for that!

All the best,
Gustavo

**Comment by daattali** [comment]
Hmm... I just installed the dev version of ggplot2 and I'm getting the same error.   Looks like ggplot2 changed something recently that broke this... :/

**Comment by daattali** [comment]
Ah this is annoying. This likely won't be a simple fix :disappointed:

**Comment by paternogbc** [comment]
Ohhh.... That might be the case because I had updated ggplot2 from github. When I installed again I used `install.packages`. So I think you are right, it is related to ggplot2 development version. 

If you need more details or any help, I am glad to contribute.

Cheers

**Comment by paternogbc** [comment]
Maybe it is not so bad. It can be some small bug inside de development version of `ggplot2`.

**Comment by daattali** [comment]
It's not really "bugs", they just completely changed the internals of ggplot2 and a lot of things just won't work anymore.  It might take a while to get things to work with the dev ggplot2 version, if you want to use ggMarginal I would stick with the CRAN ggplot2 version

**Comment by paternogbc** [comment]
Ok... so the problem is deeper! Sorry for that. 
For the shiny apps then I will stick with the last cran release from ggplo2. 

Hope you find a easy way out because ggExtra is a very nice package!

All the best,
Cheers

**Comment by daattali** [comment]
Reported a few bugs on ggplot2, hopefully will help maybe this fix easier

https://github.com/hadley/ggplot2/issues/1316

**Comment by paternogbc** [comment]
Well not so bad then. 

I am sure Hadley can provide some insights about the Bugs or possible ways to fix it.

**Comment by paternogbc** [comment]
I Just checked my package [sensiPhy](https://github.com/paternogbc/sensiPhy), which heavily depends on ggplot2 for ploting summary results!
Many errors comming with the dev version! :disappointed:

**Comment by daattali** [comment]
Yeah they've done tons of internal refactoring and external changes as well. It'll be a bit painful.

**Comment by paternogbc** [comment]
Actually, for me this was good because we are organizing the first CRAN submission around september, Now I can delay the submission and fix the bugs before.

**Comment by daattali** [comment]
The main issue I spent a lot of time on and still couldn't fix is making sure the margins are preserved in marginal plots.  Seems to potentially be a bug in ggplot2 https://github.com/hadley/ggplot2/issues/1317


Thanks @paternogbc for reporting the issue, gives me a chance to see all the much deeper issues with the new ggplot :)

**Comment by paternogbc** [comment]
So I just updated ggExtra and did some tests with my shiny app that uses `ggMarginal`. The major problems seems to be fixed. There is just some small overlap of the marginal plots inside the orginal axis. 

You welcome @daattali, I am glad that it helped. ;) 

I will keep doing more tests If I find anything new I`ll let you know.

**Comment by daattali** [comment]
Yep, the problem you mention is exactly the one that I can't seem to fix and I reported a bug to ggplot2 about the margins.  Hopefully everything other than that alignment is fixed. Glad to know it seems to be working better, do let me know if you find anything else strange if it's small.  Thanks!

**Comment by daattali** [comment]
@paternogbc I think I was able to fix all issues, including the alignment issue. When you have time, if you could test ggMarginal with the new ggplot2 version, let me know if it works

**Comment by paternogbc** [comment]
@daattali great news, thanks for the fix. I'll update and keep on some tests. 
I let you know if I find anything strange.
