### ISSUE TITLE
Travis randomly fails sometimes 

### ISSUE THREAD

**Issue by crew102** [daattali/ggExtra#140]

**Comment by daattali** [comment]
Is this not just one of life's great mysteries that are meant to remain unsolved?

**Comment by crew102** [comment]
Haha, that's what it feels like

**Comment by crew102** [comment]
So the issue here is that we are relying on the github API to install the latest version of ggplot2, and we're running into one of the API's throttling limits during the build. I implemented the solution mentioned here - https://github.com/r-lib/remotes/issues/210#issuecomment-448582301, and that seemed to fix the build for my Travis account. Can you do the same for your Travis account? 

I have one small change to #139 that I need to make. Once you add the `GITHUB_PAT` envvar to your travis settings for ggExtra, I'll add that commit to the PR and we can see if the build passes.

**Comment by daattali** [comment]
That does sound like a sensible reason for those failures. Thanks for investigating. I've added the envvar to my travis, let's try the new build
