### ISSUE TITLE
ggExtra with facets 

### ISSUE THREAD

**Issue by MarcinKosinski** [daattali/ggExtra#15]
Is it possible to use your fantastic package to create a plot described in this [question](http://stackoverflow.com/questions/32564695/scatterplots-with-density-and-correlations-in-ggplot2) :)?

**Comment by daattali** [comment]
Oh geez that looks scary to implement. Unfortunately no :stuck_out_tongue:  
If someone wants to attempt tackling this, they're welcome to do it and submit a pull request when ready. But dealing with facets is extremely hard and I doubt I'll ever implement something like this. Fair question though. Sorry :)

**Comment by MarcinKosinski** [comment]
Someone has answered my question and there appears to be such package and
functionality :)

>
> Have you considered the GGally package available on CRAN? It offers the
ggpairs function which can generate plots > similar to the one you show. It
also allows ggplot2 and GGally objects to be combined in several ways
>

2015-09-14 18:57 GMT+02:00 Dean Attali <notifications@github.com>:

**Comment by daattali** [comment]
Phew, awesome! Thanks for mentioning the package in case someone else is looking for this in the future
