### ISSUE TITLE
Does ggExtra provide normal fitting to marginal histograms?

### ISSUE THREAD

**Issue by sonic220** [daattali/ggExtra#155]
The ggExtra provides beautiful a solution to place marginal histograms. However, my work frequently requires fitting of this marginal histograms. It would be nice if ggExtra could do it but it seems that it cant. 

Is there anyway that I can do it or will ggExtra provide such option soon?

**Comment by crew102** [comment]
Sorry for the delay, I must of missed this. So you're wanting for the marginal plot (i.e., histogram) to be transformed in some way, making it follow more of a normal distribution? If so, I would suggest you transform the input data first, then call ggMarginal
