### ISSUE TITLE
`Error: no layers  in the plot` still occures for gridExtra_0.9.1

### ISSUE THREAD

**Issue by MarcinKosinski** [daattali/ggExtra#16]
`Error: no layers  in the plot` still occures when you have an old version of gridExtra (it does not work for me for version gridExtra_0.9.1) so you should ensure that user has at least version 2.0.0 of gridExtra. Can you fix this somehow or add it to the vignette/info/description?

**Comment by daattali** [comment]
Thanks,will look into it. Can you show your entire `sessionInfo()` please

**Comment by daattali** [comment]
@MarcinKosinski I'm pretty sure I spent a lot of time into ensuring it'll work with the old `gridExtra` version.  Can you let me know what the problem is and show me your `sessionInfo`?

**Comment by MarcinKosinski** [comment]
Hi, I was trying to reproduce this bug but I can't. The function works properly now
Maybe I had another package loaded to the NAMESPACE that was in conflict with `ggExtra` but I can't figure it our which package is was (even running the same script but at new session).

So maybe it was caused by my session that had too many packages loaded. Now it works fine
