### ISSUE TITLE
Reconsider which versions of ggplot2 we test under?

### ISSUE THREAD

**Issue by crew102** [daattali/ggExtra#161]
I'm wondering if testing under all ggplot2 versions since 2.2.0 is really worth it? For example, maybe we should just test under the latest couple versions. I guess there could be people out there who are using both ggMarginal and an older version of ggplot2 who would be impacted if we introduced a bug that is apparent only in their older version, but it seems unlikely.

**Comment by daattali** [comment]
I've been having similar thoughts because it finally clicked to me recently that the tidyverse mantra is to always be up to date on ALL packages, and if one package is slightly outdated than it's normal to expect problems.

So yes, since this package relies on ggplot2, it would make sense to just keep up with the latest CRAN version

**Comment by crew102** [comment]
KK, I'll get around to refactoring test code sometime soon.

**Comment by crew102** [comment]
Hey Dean, so just to confirm, you're thinking we only test under the latest CRAN version of ggplot2? I could see an argument for testing under the last few versions (definitely not the 5+ version overkill we do right now) in addition to the latest CRAN version, but I see your point re: tidyverse mantra, and also we could really simplify the test code too if we only test under the latest CRAN version.

**Comment by daattali** [comment]
I'd say it's sufficient to do the latest CRAN version plus the oldest version with the previous major or minor number.

If current version is 3.4.0 then test the latest and also 3.3.0

When current version advances to 3.4.1/3.4.2/3.4.3 etc then only test the latest and 3.3.0

If after 3.4.x it'll jump to 4.x.x then test the latest plus 3.4.0

**Comment by crew102** [comment]
Makes sense

**Comment by daattali** [comment]
Fixed
