### ISSUE TITLE
Add statistics via ggstat or ggpubr ?

### ISSUE THREAD

**Issue by SgtVil** [daattali/ggExtra#163]
Hi, first of all thx for this nice and easy package
Do you think it will be possible to had the stats on the function ? It's very usefull to display stats for the boxplot between groups in microbiota studies or else. 
For now I'm doing it manually but I think it would be a nice feature for your package

Cheers,

Rémy

**Comment by daattali** [comment]
Hi Rémy, unfortunately I'm not intimately familiar with {ggstat} or {ggpubr}, so I won't be adding support for them. If you feel inclined to take on the task of implementing this feature, I'd be happy to discuss it

**Comment by SgtVil** [comment]
It would be with great pleasure but to be honest I think I'm not there yet in terms of programming. When I feel armed enough for some programming task I will let you know. 
Anyway thx again
Have a nice day

**Comment by daattali** [comment]
I'm going to close this issue since realistically I don't think anyone else is going to tackle this. Feel free to send a PR or re-open in the future if you want to try
