### ISSUE TITLE
ggMarginal support for groupShape = T

### ISSUE THREAD

**Issue by taylorreiter** [daattali/ggExtra#167]
Hello! I'm writing to ask whether it would be feasible/in the spirit of ggMarginal to support histograms based on shape type. 

I have the following scatter plot:
<img width="763" alt="Screen Shot 2022-05-02 at 3 48 44 PM" src="https://user-images.githubusercontent.com/23057646/166338996-7b26de45-c1f0-4318-9f19-7a8e13c361ff.png">

I would like to add marginal density curves based on the shape, `status`. 

I imagine mapping shape <-> ggMarginal color may be difficult. Perhaps having a line type that was based on the shape, or in cases like the above, having on histogram filled in and one not?

I totally understand if this isn't feasible, but I thought I'd ask!

**Comment by daattali** [comment]
Sorry, only grouping by colour is supported. If you really wanted to you could modify the source code to work for shapes too by looking how we do it for colours, but I prefer not to add that into the package because then there would be a laundry list of arguments
