### ISSUE TITLE
Variable boxplot size and order

### ISSUE THREAD

**Issue by ga01** [daattali/ggExtra#174]
Hi, 
Great package; I found a weird behaviour with boxplots, it seems that their size and order can vary, even when the same factors are plotted on different figures. I did not find a way of changing this behaviour; is there a way of switching off this feature, and having similarly sized and ordered boxes?

Best wishes, 
George

![img1](https://user-images.githubusercontent.com/35599604/215781539-6895f645-d754-4641-9d64-58799bf69731.png)
![img2](https://user-images.githubusercontent.com/35599604/215781578-b5643620-f269-45d4-ae31-7e711d9df374.png)

**Comment by ga01** [comment]
Hi 
Yes, it was largely the same problem, I should have found it myself. Installing the latest ggExtra version fixes most issues, there is one minor issue that remains: the order of the boxes is not the same as the order of the factors on the main plot, at least when there are three factors (probably with more as well). So if I have three factors, A, B and C, then the order of the boxes in the side-boxplot is B, A, C. It is consistent across different plots with the same factors, the color-coding is correct, so this is not an error just a minor cosmetic issue, but still might be worth fixing.

Best wishes, 
George

**Comment by daattali** [comment]
If this issue is fixed, I'm closing this issue. Please open a separate issue for the other problem you describe!
