### ISSUE TITLE
merge groups for ggmarginal

### ISSUE THREAD

**Issue by Yogesh1-11** [daattali/ggExtra#178]
hi is it possible to supply separate grouping to ggmarginal than the scatter plot. For example my PCA has four dots coloured individually lets say A,B C, D. but in marginal on x axis i want to make only two density plot of AB and CD while on Y axis i want to make two density plots of AC and BD. hope i could make it clear.

**Comment by daattali** [comment]
There's no built in way to do that. The groupings for marginal plots are automatically inferred from the grouping used in the main plot.

**Comment by Yogesh1-11** [comment]
Oh ok. Also it will be great if you could extend marginal display of
dendrograms.

**Comment by daattali** [comment]
This package is mostly in maintenance mode, I highly doubt a new feature for dendograms will be implemented -- unless you or someone else wants to tackle that! I'm closing this issue because there are no such plans
