### ISSUE TITLE
Not default theme set makes grid appear on marginal density

### ISSUE THREAD

**Issue by Rekyt** [daattali/ggExtra#19]
Hi,

When using a `theme_set()` different from default (for example `theme_set(theme_bw())`), the marginal densities or histogram use the same theme and thus have grids and lines appearing.

![rplot](https://cloud.githubusercontent.com/assets/5593751/11034956/89cf11ec-86ef-11e5-84e7-31f16445d943.png)

**Comment by daattali** [comment]
Thanks. Note for future self to reproduce:

```
library(ggplot2)
library(ggExtra)
theme_set(theme_bw())
p <- ggplot(mtcars, aes(wt, mpg)) + geom_point()
ggMarginal(p)
```
