### ISSUE TITLE
legends offsets histograms

### ISSUE THREAD

**Issue by gatcbiotech** [daattali/ggExtra#23]
Hi,
when you have legends, the marginal plots are not displayed correctly to the axis. See the attached files for an example.
Regards,
Yadhu

![without legend](https://cloud.githubusercontent.com/assets/16257570/14241340/51079102-fa4b-11e5-83ac-7a7b58f640a0.png)
![withlegend](https://cloud.githubusercontent.com/assets/16257570/14241342/54ace0fa-fa4b-11e5-965c-9547dd272aff.png)

**Comment by daattali** [comment]
Thanks for the report. Please provide some code for a minimal reproducible example if you could. I'll take a look in a couple weeks after I finish my thesis and defense

**Comment by gatcbiotech** [comment]
myplot <- ggplot(mtcars, aes(wt, mpg)) + geom_point(aes(color=vs))
ggExtra::ggMarginal(
  p = myplot,
  type = 'histogram',
  margins = 'both',
  size = 5,
  col = 'black',
  fill = 'gray'
)

**Comment by daattali** [comment]
I just tried looking into this a little bit, and I'm not sure how to fix this.  I'm not sure how to tell if a ggplot object has a legend or not, if anyone knows a way to figure that out, or has another fix for this issue, I'll welcome any ideas

**Comment by crew102** [comment]
I can take a shot at this over the weekend. Pretty sure I know how to fix.

**Comment by daattali** [comment]
@crew102 that'd be great

**Comment by daattali** [comment]
Fixed thanks to @crew102
