### ISSUE TITLE
On smaller monitors, results plot is "cut-off" at bottom x-axis. 

### ISSUE THREAD

**Issue by sfd99** [daattali/ggExtra#24]
**NOTE:**  Problem only happens _on smaller_ monitors.
My 2nd monitor, where I run R studio, is 14 inches diag.
(No problem on larger monitors)

Using your great  mtcars **ggExtra** _**Margins**_ example,
in the latest Rstudio / Linux.

From the _Console panel_,
this works ok:

library(ggplot2)
library(ggExtra)
myplot <- ggplot(mtcars, aes(wt, mpg)) + geom_point()

But...using the Rstudio "addin"
from the _Code panel_,
shows:
http://imgur.com/epvDELb

_See?_
The bottom part of the plot is "cut-off" (below  mpg=10)
...can not see the wt  x-axis.

So yes, everybody with smaller monitors
may have that problem.

_**Q:**_  (possible solution?)
Is there a way
to make the results Margins popup window,
_"user-resizable_"?.

I'm sure that if I could use the **mouse**
to _"resize" that popup_,
the hidden parts will re-appear OK,
even on smaller monitors.

**_btw:_**
There is lots of unused screen space
_around_ that popup,
so allowing the user to _mouse-resize_ it,
would certainly solve the problem! :-)

**Comment by daattali** [comment]
I'm also on a 14 inch monitor and don't have that problem. I suspect the problem stems from a small screen resolution - what's the resolution you're using?  Regardless, I'll try to fix it

**Comment by daattali** [comment]
@sfd99 can you please test again on your monitor with the latest github version? Should be fixed

**Comment by sfd99** [comment]
Resolution on the  (secondary) 14'' monitor:
1024 X 768 (4:3)
----------------------
**_btw:_**  (see my + recent email for details):

  mynewplot <- ggMarginalGadget(myplot) WORKS FINE now!.

But.... the other alternative method (using the Rstudio "addin"),
 ie:  highlight the:
       myplot <- ggplot(mtcars, aes(wt, mpg)) + geom_point()

gives this message:
> ggExtra:::ggMarginalGadgetAddin ()
Error: 'x' should be a list of {range, text} pairs. 

pls, let me know by email...(faster exchange for me). :-)
