### ISSUE TITLE
ggMarginal(p) invalidates the boldness of the main plot title

### ISSUE THREAD

**Issue by pinetree1** [daattali/ggExtra#30]
ggMargin is great. But it changes bold main title to plain text, which is not desired.

p <- ggplot(mtcars, aes(x=wt, y=mpg)) + geom_point() + theme_bw() + 
labs(title="Main Title", y="MPG") + 
theme(plot.title=element_text(face="bold", size=14), 
axis.title.y=element_text(face="bold", size=14))

p's main title and y are bold.

ggMarginal(p, margins="y", size=4)

Now main title is changed to plain text. The y title font face is not affected. Can you maintain the font face of main title?

**Comment by daattali** [comment]
fixed
