### ISSUE TITLE
ggMarginal() not working with ggplot2.2.1.900

### ISSUE THREAD

**Issue by tanerumit** [daattali/ggExtra#38]
I am trying to replicate the example:

```{r}

library("ggplot2")
library("ggExtra")

set.seed(30)
df <- data.frame(x = rnorm(500, 50, 10), y = runif(500, 0, 50))
p <- ggplot(df, aes(x, y)) + geom_point()

ggMarginal(p)

```

Which results the following error:

Error: Don't know how to add o to a plot
In addition: Warning message:
In mean.default(getLimits(pbTop, "y")) :
  argument is not numeric or logical: returning NA

----
Session info:
```{r}
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.3

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggExtra_0.6.1      ggplot2_2.2.1.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9      digest_0.6.12    assertthat_0.1   mime_0.5         grid_3.3.2      
 [6] plyr_1.8.4       R6_2.2.0         xtable_1.8-2     gtable_0.2.0     scales_0.4.1    
[11] lazyeval_0.2.0   miniUI_0.1.1     labeling_0.3     tools_3.3.2      munsell_0.4.3   
[16] shiny_1.0.0.9000 httpuv_1.3.3     colorspace_1.3-2 htmltools_0.3.5  tibble_1.2 
```

**Comment by daattali** [comment]
You seem to be right, updating from ggplot2 2.2.1 to 2.2.1.9000 seems to be
broken.  Every time ggplot is updated, it breaks ggmarginal, makes me very
sad :(

I'll try to take a look when I find some free time, thanks for reporting!

---
Founder & Lead Consultant
AttaliTech Ltd
http://deanattali.com/shiny

**Comment by crew102** [comment]
Looks like it's just a matter of a ggplot2 restructuring/renaming components of the `layout` object...E.g., `layout$panel_scales$y` should be changed to `layout$panel_scales_y` in ggMarginal. I would suggest a more thorough refactoring of ggMarginal, though, so that its easier to fix these kinds of problems in the future. I can take care of that sometime next week.

**Comment by daattali** [comment]
A refactoring is definitely needed, but I'm not that familiar with ggplot2
especially since 2.0 came out. I would be very happy to get a PR!

**Comment by tanerumit** [comment]
Thanks!!
