### ISSUE TITLE
Initial questions

### ISSUE THREAD

**Issue by crew102** [daattali/ggExtra#39]
Hi there -

Two initial questions I have come across while refactoring:

1. Are we sure that this is needed for ggplot2 V 2.2 and above (lines 96-99 of ggMarginal.R):
````
 # after ggplot2 v1.0.1, layers became strict about parameters
  if (type == "density") {
    extraParams[['fill']] <- NULL
}
````
 I'm getting the behavior that I would want (a warning from ggplot: "Warning: Ignoring unknown parameters: fill") when I drop those lines from ggMarginal and I run this code:
````
p <- ggplot2::ggplot(mtcars, ggplot2::aes(wt, mpg)) + ggplot2::geom_point()
ggExtra::ggMarginal(p, type = "density", fill = "black")
````
I also don't understand why this line would be needed for a density geom and not boxplot/histogram but that's probably just my ignorance. 

2. Regarding this bit of code (lines 113-143 of ggMarginal.R):

````
if (missing(p)) {
    if (missing(data) || missing(x) || missing(y)) {
      stop("`data`, `x`, and `y` must be provided if `p` is not provided",
           call. = FALSE)
    }
    p <- ggplot2::ggplot(data, ggplot2::aes_string(x, y)) + ggplot2::geom_point()
    x <- as.symbol(x)
    y <- as.symbol(y)
  } else {
    if (missing(data)) {
      if (methods::is(p$data, "waiver")) {
        stop("`data` must be provided if it is not part of the main ggplot object",
             call. = FALSE)
      }
      data <- p$data
    }
    if (length(p$mapping) == 0) p$mapping <- p$layers[[1]]$mapping
    if (margins != "y" && missing(x)) {
      if (is.null(p$mapping$x)) {
        stop("`x` must be provided if it is not an aesthetic of the main ggplot object",
             call. = FALSE)
      }
      x <- p$mapping$x
    }
    if (margins != "x" && missing(y)) {
      if (is.null(p$mapping$y)) {
        stop("`y` must be provided if it is not an aesthetic of the main ggplot object",
             call. = FALSE)
      }
      y <- p$mapping$y
    }
  }
````
...We already make sure in the `if` statement that the user provided `data`, `x`, and `y` if they didn't provide `p`. Under what circumstance could they pass this test and be thrown an error in the `else` block? In other words, under what circumstances would the user supply a ggplot object `p` but you still need them to supply `x`, `y`, or `data`? It looks like it may be an assertion that you ggplot still keeps `x`, `y`, and `data` where you think they will be in the plot object, but it's hard to tell if you're testing that or user params.

**Comment by crew102** [comment]
Just saw that the density plots are actually line plots with a geom_density, hence the check on the `fill` param. You can disregard question 1.

**Comment by daattali** [comment]
You're really taking a good look at the code! I hope the documentation and the code are friendly enough to a third party. To answer question 2: if you look at the line in the middle of that chunk:

```
if (length(p$mapping) == 0) p$mapping <- p$layers[[1]]$mapping
```

I try to ensure there's a mapping to use X and Y from if none is provided. This would happen when you do something like `ggplot(iris) + geom_point(aes(Sepal.Width,Sepal.Length))` - in this case, the main plot object does not have an X and Y mapping, but I was able to borrow it from the first layer. However, there are more complex ggplot calls where the main plot doesn't have a mapping and neither does the first layer, in which case x and y are needed. Does that help?

**Comment by crew102** [comment]
> However, there are more complex ggplot calls where the main plot doesn't have a mapping and neither does the first layer, in which case x and y are needed

Didn't know this, thanks, that answers.

**Comment by daattali** [comment]
And to be honest, I can't give you such ggplot calls right now, because I've been very out of touch with this package and ggplot for a while. But when I made the package I did run into that issue, that much I do know :)
