### ISSUE TITLE
Add visual tests for ggMarginal (all versions of ggplot2 >= 2.2.0)

### ISSUE THREAD

**Issue by crew102** [daattali/ggExtra#42]

**Comment by daattali** [comment]
The harder part here is figuring out how to get a system in place that **can** handle testing multiple versions of ggplot. Once that system is in place, actually adding the tests is the easy part :)

For reference https://gist.github.com/jimhester/d7aeb95bbed02f2985a87c2a3ede19f5 (thanks @jimhester)

**Comment by jimhester** [comment]
FWIW I will probably be adding a `with_package_versions()` function to withr that you could use for this, assuming you can wait a bit for the next withr release.

**Comment by daattali** [comment]
Awesome!
