### ISSUE TITLE
Add webhook to trigger build when new version of ggplot2 passes 

### ISSUE THREAD

**Issue by crew102** [daattali/ggExtra#44]

**Comment by crew102** [comment]
I did some research on this and I don't think it's possible to trigger based on another users repo...Do you know anyone who might know?

**Comment by daattali** [comment]
To be honest, I haven't done my research on the topic and I don't know too much about it. Let's see if someone on twitter knows the answer off the top of their heads (I assume they will either have an easy answer or a flat out "no")

https://twitter.com/daattali/status/854069187404288000

**Comment by daattali** [comment]
Looks like the solution is to use Cron Jobs in travis, to automatically run the tests once per day/week

https://docs.travis-ci.com/user/cron-jobs/

**Comment by crew102** [comment]
I set this up for my travis account many moons ago and forgot to mention it. I think we can close this.
