### ISSUE TITLE
ggMarginal should carry theme of title through

### ISSUE THREAD

**Issue by crew102** [daattali/ggExtra#46]
Right now `ggMarginal`  only carries the color and font face of the scatter plot's title through to the final plot. The text grob that we use for a title in the final plot is created here:
```
    title <- grid::textGrob(
      pb$plot$labels$title,
      gp = grid::gpar(col = pb$plot$theme$plot.title$colour,
                      fontsize = 16, fontface = pb$plot$theme$plot.title$face)
    )
```
It's easy to pull out the ggplot2 `titleGrob` that contains all of the theme elements desired by the user, and drop that grob in instead of using `grid::textGrob`. I will include this in the next PR.

**Comment by daattali** [comment]
Thank you, this PR is going to be loved by many!
