### ISSUE TITLE
X-axis label too close to edge of plot - need a bit of margin because some letters get cut off

### ISSUE THREAD

**Issue by daattali** [daattali/ggExtra#49]
At some point in the past year, the bottom margin of the x axis label has disappeared. The label is stuck to the bottom of the image without any space, and any letters that go lower the the standard line (such as "g" "j" "p" "q" "y") are cut off.

I'm not sure if this is because of newer ggplot version, or because of the refactoring from https://github.com/daattali/ggExtra/pull/26

**Comment by crew102** [comment]
Hmm, is this what you are talking about?

![temp](https://cloud.githubusercontent.com/assets/11220793/25453804/49261a84-2a98-11e7-88fe-fdc9edf15497.png)

It looks like there is zero margin around the x and y axis (both in refactored version and non. Note, this is the refactored version). I'm not getting any letters cut off in either version, though. Should we add padding around the plot?

**Comment by daattali** [comment]
Looks like it might be an RStudio Viewer issue maybe? Running this code:

```
p <- ggplot2::ggplot(mtcars, ggplot2::aes(wt, mpg)) + ggplot2::geom_point()
ggMarginal(p + xlab("gpjy"))
```

I get this in rstudio

![image](https://cloud.githubusercontent.com/assets/952340/25454336/1a100366-2a9a-11e7-86f2-cde7152bb053.png)

But if I export the image, then the bottom is not cut off. You don't get that in rstudio?

**Comment by crew102** [comment]
Incidentally I just updated to R 3.4.0 today and the RStudio version I run doesn't support the latest version of the R graphics engine that is used in 3.4.0. However, using graphics engine version 2 I still don't get cutoff:

![1](https://cloud.githubusercontent.com/assets/11220793/25456799/f641771e-2aa1-11e7-9e15-a9392aea235d.png)

I think it's probably the ggplot2 version that's doing it. What version are you using? I'm at 2.2.1.

It also looks like you're getting plenty of margin space for the y-axis, which mine doesn't show.

**Comment by daattali** [comment]
I'm also at ggplot2 2.2.1

If we can't find the exact cause for these discrepancies easily, I wouldn't bother with it too much at this time. It's good to have this documented and we can come back to it later

**Comment by crew102** [comment]
I think I see what's going on here... This is using RStudio v 1.0.143:

![untitled](https://cloud.githubusercontent.com/assets/11220793/25641255/2cbd1fe6-2f61-11e7-983d-f27f0fa2e8b1.png)

Looks like when the plot is confined to the "Plots" tab as it is on the right hand side, the x-axis title is getting cut off. When you "zoom" (or print to a device - e.g., pdf, png) as is shown on the left hand side, something happens with the sizing of the graph where we don't see the problem. 

 I think we should add padding,  as most people will view plots interactively through the plots tab and will wonder why it's getting cut off.

Also, there's this: https://support.rstudio.com/hc/en-us/articles/200488548-Problem-with-Plots-or-Graphics-Device

**Comment by crew102** [comment]
Strangely enough the Plots tab in RStudio server doesn't seem to have the issue that the desktop version does - at least for the graphs I've looked at.

**Comment by daattali** [comment]
I'm fairly convinced this is indeed an RStudio bug. Adding very minimal padding could be a good idea

**Comment by daattali** [comment]
Did you add this minimal bottom padding to #40 ?

**Comment by crew102** [comment]
Going to address in separate PR

**Comment by daattali** [comment]
Sounds good
