### ISSUE TITLE
Remove external border when combining several graphs

### ISSUE THREAD

**Issue by ervanSTRI** [daattali/ggExtra#53]
Hi, 

I couldn't find the way not to plot the outer frame when combining graphs through ggplot2 + ggExtra + cowplot. I am not sure where I have to tell R, but suspect the issue to lie in ggExtra. Here is an example:
require(ggplot2)
require(cowplot)
require(ggExtra)

# Creat a graph
A <- ggplot(mpg, aes(x = cty, y = hwy, colour = factor(cyl))) +     geom_point(size = 2.5)

# Add marginal histogram
B <- ggExtra::ggMarginal(A,type = 'histogram', margins = 'x', size = 9)

# Combine through cowplot
combo <- plot_grid(B,B,labels=c("A","B"))
plot(combo) # looks fine

# Re-combine through cowplot
plot_grid(B,combo,ncol=1,rel_heights = c(2,3))

The question is also posted on Stackoverflow, [here](http://stackoverflow.com/questions/43900867/r-remove-border-when-plotting-with-ggplot2-ggextra-cowplot).

Thanks for any help!

**Comment by daattali** [comment]
I cannot reproduce. Using your exact code, I see this:

![image](https://cloud.githubusercontent.com/assets/952340/25918670/4223c670-359a-11e7-8be8-c134315b8d19.png)

ggExtra does not place any outline borders, so it's either cowplot or something in your system/rstudio
