### ISSUE TITLE
Support for marginal violin plots

### ISSUE THREAD

**Issue by Alanocallaghan** [daattali/ggExtra#62]

**Comment by daattali** [comment]
why did you close this issue? I think it's a good idea

**Comment by Alanocallaghan** [comment]
I thought it had a large overlap with density plots, but on reflection there are additional features of a violin plot that would be useful.

**Comment by daattali** [comment]
Yes it could be useful. It should be fairly straight forward to add support for it, I think it's essentially a copy of how boxplots work. If anyone wants to submit a PR, I'd happily accept
