### ISSUE TITLE
Regression in getVarDF

### ISSUE THREAD

**Issue by crew102** [daattali/ggExtra#71]
Looks like I introduced a bug when fixing #67. The following code now doesn't run during testing due to the new bug:

```r
library(ggplot2)
library(ggExtra)

p <- ggplot(data = mtcars) +
  geom_point(aes(x = wt, y = drat, colour = gear)) +
  ggtitle("pretty sweet title",
                   subtitle = "not a bad subtitle either") +
  theme(plot.title = element_text(colour = "red"))

ggMarginal(p = p)
```

PR on the way.

**Comment by daattali** [comment]
Is this the reason for the failing tests on travis now (that have always been failing but maybe now they'd pass)? Anyway, thanks for catching that

**Comment by crew102** [comment]
looking into it now

**Comment by daattali** [comment]
travis will inform us soon enough https://travis-ci.org/daattali/ggExtra/builds/286744817
