### ISSUE TITLE
scale_x_continuous with limits set causes `ggMarginal` to crash

### ISSUE THREAD

**Issue by lukauskas** [daattali/ggExtra#80]
Have a look at the following snippet:

```R
require('ggplot2')
require('ggExtra')

p <- ggplot(mtcars) 

p <- p + geom_point(aes(wt, mpg), show.legend=FALSE) 
p <- p + scale_x_continuous(limits=c(0, 2))

# Uncomment me:
#p <- ggMarginal(p, type='boxplot')

ggsave('test.png', plot=p, w=5, h=5, units='in')
```

The way it stands right now it produces the following plot:

![image](https://user-images.githubusercontent.com/108413/32519624-a8ad9fc2-c40d-11e7-80f6-9b734b0357bb.png)

If you uncomment `ggMarginal` line, however, the following error is thrown:

```R
Error in if (is.double(data$x) && !has_groups(data) && any(data$x != data$x[1L])) { : 
  missing value where TRUE/FALSE needed
```

and no plot is produced.

Wish I could help more, but this is all I have.

My R version is 3.4.1 (2017-06-30)
And I just ran `install_github('daattali/ggExtra')` half an hour before posting this issue.

**Comment by crew102** [comment]
Hi @lukauskas, thanks for reporting this issue. This issue is related to #81, which I'll try to get to sometime this or next week.

**Comment by daattali** [comment]
fixed
