### ISSUE TITLE
Reformat ggExtra code

### ISSUE THREAD

**Issue by crew102** [daattali/ggExtra#87]
I recently discovered `styler` (http://styler.r-lib.org/), which makes it painless to format a bunch of code to be consistent with tidyverse styling (which I generally try to adhere to these days but not so much in the past). Would you mind if I run styler on ggExtra? 
* Format test code too

**Comment by daattali** [comment]
Awesome, I didn't know it was released on CRAN already. Yes, I 100% support that coding style!

**Comment by crew102** [comment]
Cool, I'll apply it to ggExtra and open up a pr after #66 is merged
