### ISSUE TITLE
ggMarginal fails if geom_abline() called before geom_point()

### ISSUE THREAD

**Issue by jimoeppen** [daattali/ggExtra#88]
A legitimate ggplot graph causes ggMarginal(...) to fail if geom_abline(...) is called before geom_point(...) with the error

Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 0, 1

If geom_point(...) is called before geom_abline(...) then it works.  Here is some example code [R 3.4.3; ggExtra_0.7; ggPlot2_2.2.1]

df <- data.frame(x = rnorm(500, 50, 10), y = runif(500, 0, 50))
p2 <- ggplot2::ggplot(df, ggplot2::aes(x, y)) +
  geom_abline(
    slope = 1,
    intercept = 0,
    linetype = "longdash",
    lwd = 1,
    colour = "black"
  ) +
  ggplot2::geom_point()

p2
ggMarginal(p2, type = "histogram")

**Comment by crew102** [comment]
Thanks for reporting this @jimoeppen. I think the fix should be straightforward. I'll look into it.

**Comment by crew102** [comment]
This issue is fixed in the latest dev version of `ggExtra`. You can install it with `devtools::install_github("daattali/ggExtra")`

**Comment by daattali** [comment]
@jimoeppen as Chris said, you need to install the github version. If you don't need it right away, you can wait a few weeks until `ggExtra` is released to CRAN

**Comment by daattali** [comment]
@jimoeppen closing this issue since it's fixed
