### ISSUE TITLE
Refactor ggMarginal to use R6

### ISSUE THREAD

**Issue by crew102** [daattali/ggExtra#90]
I think ggMarginal needs another refactoring. Would you be amenable to ggExtra importing R6 if I wanted to use it when re-working ggMarginal?

Also needs more thorough commenting throughout code (which I've been neglecting), given how much seemingly random stuff happens in ggMarginal.

**Comment by daattali** [comment]
R6 is pretty good and lightweight, so there's nothing against it. What would be the main benefit, to save state so that there aren't a ton of variables being constantly passed around?

**Comment by crew102** [comment]
Yep, exactly

**Comment by daattali** [comment]
Sure!
