### ISSUE TITLE
Issues with groupColour/groupFill when `colour` or `fill` param are supplied

### ISSUE THREAD

**Issue by daattali** [daattali/ggExtra#93]
When supplying a `colour` it's not a huge deal, but essentially is overwrites the colour mapping:
```
p <- ggplot(mtcars, aes(x = wt, y = drat, colour = factor(vs))) +
    geom_point()

ggMarginal(p, groupColour = TRUE, colour = "red")
```

![image](https://user-images.githubusercontent.com/952340/36286405-9c02c5c2-127d-11e8-8bae-6f5424bdc706.png)

Same thing happens with `fill`.

But when using both together, it looks like the the grouping is completely for fill:

```
ggMarginal(p, groupColour = TRUE, groupFill = TRUE, colour = "red", fill = "blue")
```

![image](https://user-images.githubusercontent.com/952340/36286496-048751ee-127e-11e8-964e-36f5a2cc7df6.png)

**Comment by daattali** [comment]
I think when groupColour is used, `colour` should always be set to NULL (even if it's provided) and same with groupFill

**Comment by crew102** [comment]
Agreed re: preference for group col/fill..we should probably throw a
warning, then null out the col/fill...the second case u gave is less
straightforward...I'll have to look into the code to see what's causing it.

**Comment by daattali** [comment]
Regardless of the cause, it would be fixed by NULLing colour/fill when
their group* argument is TRUE. I'd go with a message rather than a warning

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by daattali** [comment]
And it needs to support users using either of `col` `color` `colour`...

**Comment by daattali** [comment]
Yes, closed, no need to make a weird workaround!
